class Constants:
    # Screen.
    SCREEN_WIDTH_PIXELS = 1_310
    SCREEN_HEIGHT_PIXELS = 640

    BACKGROUND_COLOR = (255, 255, 255)

    # Field.
    FIELD_WIDTH_METERS = 16.54
    FIELD_HEIGHT_METERS = 8.02

    FIELD_DRAWING_FILE_PATH = 'field_drawing.png'

    # Conversions.
    WIDTH_METERS_PER_PIXEL = FIELD_WIDTH_METERS / SCREEN_WIDTH_PIXELS
    HEIGHT_METERS_PER_PIXEL = FIELD_HEIGHT_METERS / SCREEN_HEIGHT_PIXELS