class Constants:
    # Screen.
    SCREEN_WIDTH_PIXELS = 1_310
    SCREEN_HEIGHT_PIXELS = 640

    BACKGROUND_COLOR = (255, 255, 255)

    # Field.
    FIELD_WIDTH_METERS = 16.54
    FIELD_HEIGHT_METERS = 8.02

    FIELD_DRAWING_FILE_PATH = 'field_drawing.png'

    # Conversions.
    WIDTH_METERS_PER_PIXEL = FIELD_WIDTH_METERS / SCREEN_WIDTH_PIXELS
    HEIGHT_METERS_PER_PIXEL = FIELD_HEIGHT_METERS / SCREEN_HEIGHT_PIXELS
    METERS_PER_INCH = 2.54 / 100.0

    # Robot.
    ROBOT_WIDTH_METERS = 31.0 * METERS_PER_INCH
    ROBOT_HEIGHT_METERS = 33.0 * METERS_PER_INCH

    ROBOT_WIDTH_PIXELS = ROBOT_WIDTH_METERS / WIDTH_METERS_PER_PIXEL
    ROBOT_HEIGHT_PIXELS = ROBOT_HEIGHT_METERS / HEIGHT_METERS_PER_PIXEL

    ROBOT_COLOR = (255, 0, 0)
    ROBOT_LINE_WIDTH = 10